apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  env: staging

resources:
  - namespace.yaml

namespace: staging

patchesStrategicMerge:
  - deployment.yaml
